name: simple_chips_input
description: Flutter package for creating chips while typing like in Gmail app.
version: 0.2.0
homepage: https://github.com/danger-ahead/simple_chips_input

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
